name: Assertions and static report

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm add -g @unlighthouse/cli puppeteer

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site www.getthit.com --budget 1 --build-static --debug --urls https://www.getthit.com/wiki/tag/website-traffic-bot
        
      - name: Deploy report to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "/home/runner/work/getthit-lighouhouse/getthit-lighouhouse/.unlighthous"        
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: RLwUl8VOHH-OjQ77dPMcljtMvrE5qFKuds4WBIdFDAk
          NETLIFY_SITE_ID: a74ab122-7377-47ab-84b3-67808603c19b
        timeout-minutes: 1
